### PR TITLE
Ditch Plyr

### PR DESCRIPTION
**Pull request by javan**

### CODE REVIEW

**Comment by vampeel** [comment]
Why was this done?

Also, the addition of `display: block` to the base `img` style broke the layout.
Screen Shot 2020-12-22 at 11 05 12 AM

I pushed up a quick fix to main.

**Comment by javan** [comment]
Oops, thanks Adam!

Plyr felt a bit too heavy for a single-page (literally one page) website. Especially along side our *without using much JavaScript* messaging.

Before:
before

After:
after

**Comment by vampeel** [comment]
I don't think it's asking too much that material changes to my work come with at least an explanation, if not discussion.

**Comment by javan** [comment]
Discussed in [a campfire chat today](https://3.basecamp.com/2914079/buckets/1037/chats/804117@3321671045), and didn't think the change warranted interrupting your vacation. Appreciate that you jumped in to help though!

**Pull request merged**
